[project]
name = "025-servicenow-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pravin Pardeshi", email = "pravin.pardeshi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115",
    "uvicorn>=0.30",
    "requests>=2.31",
    "pydantic>=2.0",
    "python-dotenv>=1.0",
]

[project.scripts]
025-servicenow-cloud = "025_servicenow_cloud:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
